version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: temple_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: temple
      POSTGRES_PASSWORD: temple123
      POSTGRES_DB: templedb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: temple_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@temple.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres

volumes:
  postgres_data:
